### ISSUE TITLE
Står still 

### ISSUE THREAD

**Issue by Toorl** [jonkpirateboy/Pass-fur-alle#1]
Efter man kör scriptet och väljer län och/eller utan stad så händer inget mer än att den startar browser och kommer till länets sida. 
"Chrome is being controlled by automated test software." 
https://bokapass.nemoq.se/Booking/Booking/Index/halland

lla län: https://polisen.se/tjanster-tillstand/pass-och-nationellt-id-kort/boka-tid-hitta-passexpedition/
Välj län. Sista delen av url t ex 'halland'. Eller tryck enter för Skåne: halland
Välj expedition. T ex 'Halmstad'. Eller tryck enter för hela länet: kungsbacka
Län:  halland
Expedition:  kungsbacka
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing time
# cleanup[2] removing zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.cp437
# cleanup[2] removing encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing posixpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing site
# destroy site
# cleanup[2] removing selenium
# destroy selenium
# cleanup[2] removing selenium.webdriver.firefox
# cleanup[2] removing types
# cleanup[2] removing enum
# cleanup[2] removing _sre
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_compile
# cleanup[2] removing _operator
# cleanup[2] removing operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing _heapq
# cleanup[2] removing heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# cleanup[2] removing _functools
# cleanup[2] removing functools
# cleanup[2] removing _locale
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing _struct
# cleanup[2] removing struct
# cleanup[2] removing binascii
# cleanup[2] removing base64
# cleanup[2] removing fnmatch
# cleanup[2] removing errno
# cleanup[2] removing zlib
# cleanup[2] removing warnings
# cleanup[2] removing _compression
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing threading
# cleanup[2] removing _bz2
# cleanup[2] removing bz2
# cleanup[2] removing _lzma
# cleanup[2] removing lzma
# cleanup[2] removing pwd
# cleanup[2] removing grp
# cleanup[2] removing shutil
# cleanup[2] removing contextlib
# cleanup[2] removing collections.abc
# cleanup[2] removing typing
# destroy typing
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing importlib
# cleanup[2] removing importlib.machinery
# cleanup[2] removing importlib.abc
# cleanup[2] removing importlib.util
# cleanup[2] removing zipfile
# cleanup[2] removing selenium.webdriver.common
# cleanup[2] removing selenium.webdriver.common.desired_capabilities
# cleanup[2] removing selenium.webdriver.remote
# cleanup[2] removing weakref
# cleanup[2] removing copy
# cleanup[2] removing pkgutil
# cleanup[2] removing selenium.webdriver.remote.bidi_connection
# cleanup[2] removing selenium.webdriver.remote.command
# cleanup[2] removing selenium.common.exceptions
# cleanup[2] removing selenium.common
# destroy selenium.common
# destroy selenium.common.exceptions
# cleanup[2] removing selenium.webdriver.remote.errorhandler
# cleanup[2] removing selenium.types
# destroy selenium.types
# cleanup[2] removing _socket
# cleanup[2] removing math
# cleanup[2] removing select
# cleanup[2] removing selectors
# cleanup[2] removing socket
# cleanup[2] removing selenium.webdriver.common.keys
# cleanup[2] removing selenium.webdriver.common.utils
# cleanup[2] removing selenium.webdriver.remote.file_detector
# cleanup[2] removing selenium.webdriver.remote.mobile
# cleanup[2] removing token
# destroy token
# cleanup[2] removing tokenize
# cleanup[2] removing linecache
# cleanup[2] removing traceback
# cleanup[2] removing _string
# cleanup[2] removing string
# cleanup[2] removing atexit
# cleanup[2] removing logging
# cleanup[2] removing _bisect
# cleanup[2] removing bisect
# destroy bisect
# cleanup[2] removing _sha512
# cleanup[2] removing _random
# cleanup[2] removing random
# cleanup[2] removing tempfile
# cleanup[2] removing ntpath
# cleanup[2] removing urllib
# cleanup[2] removing urllib.parse
# cleanup[2] removing pathlib
# destroy pathlib
# cleanup[2] removing importlib.resources
# cleanup[2] removing certifi.core
# cleanup[2] removing certifi
# cleanup[2] removing __future__
# destroy __future__
# cleanup[2] removing urllib3.packages
# cleanup[2] removing urllib3.packages.six
# cleanup[2] removing urllib3.packages.six.moves
# cleanup[2] removing http
# cleanup[2] removing email
# cleanup[2] removing email.errors
# cleanup[2] removing email.quoprimime
# cleanup[2] removing email.base64mime
# cleanup[2] removing quopri
# cleanup[2] removing email.encoders
# cleanup[2] removing email.charset
# cleanup[2] removing email.header
# cleanup[2] removing _datetime
# cleanup[2] removing datetime
# cleanup[2] removing locale
# cleanup[2] removing calendar
# cleanup[2] removing email._parseaddr
# cleanup[2] removing email.utils
# cleanup[2] removing email._policybase
# cleanup[2] removing email.feedparser
# cleanup[2] removing email.parser
# cleanup[2] removing uu
# cleanup[2] removing email._encoded_words
# cleanup[2] removing email.iterators
# cleanup[2] removing email.message
# cleanup[2] removing _ssl
# cleanup[2] removing ssl
# cleanup[2] removing http.client
# cleanup[2] removing urllib3.packages.six.moves.http_client
# cleanup[2] removing urllib3.exceptions
# cleanup[2] removing urllib3._version
# cleanup[2] removing urllib3.contrib
# cleanup[2] removing urllib3.contrib._appengine_environ
# cleanup[2] removing urllib3.util.wait
# cleanup[2] removing urllib3.util.connection
# cleanup[2] removing urllib3.util.request
# cleanup[2] removing urllib3.util.response
# cleanup[2] removing urllib3.util.retry
# cleanup[2] removing _hashlib
# cleanup[2] removing _blake2
# cleanup[2] removing _sha3
# cleanup[2] removing hashlib
# cleanup[2] removing hmac
# cleanup[2] removing urllib3.util.url
# cleanup[2] removing urllib3.util.ssltransport
# cleanup[2] removing urllib3.util.ssl_
# cleanup[2] removing urllib3.util.timeout
# cleanup[2] removing urllib3.util
# cleanup[2] removing urllib3.util.proxy
# cleanup[2] removing urllib3._collections
# cleanup[2] removing ipaddress
# cleanup[2] removing urllib3.util.ssl_match_hostname
# cleanup[2] removing urllib3.connection
# cleanup[2] removing _queue
# cleanup[2] removing queue
# cleanup[2] removing mimetypes
# cleanup[2] removing urllib3.fields
# cleanup[2] removing urllib3.filepost
# cleanup[2] removing urllib3.packages.six.moves.urllib
# cleanup[2] removing urllib3.packages.six.moves.urllib.parse
# cleanup[2] removing urllib3.request
# cleanup[2] removing urllib3.response
# cleanup[2] removing urllib3.util.queue
# cleanup[2] removing urllib3.connectionpool
# cleanup[2] removing urllib3.poolmanager
# cleanup[2] removing urllib3
# cleanup[2] removing platform
# cleanup[2] removing _json
# cleanup[2] removing json.scanner
# cleanup[2] removing json.decoder
# cleanup[2] removing json.encoder
# cleanup[2] removing json
# cleanup[2] removing selenium.webdriver.remote.utils
# cleanup[2] removing selenium.webdriver.remote.remote_connection
# cleanup[2] removing _uuid
# cleanup[2] removing uuid
# cleanup[2] removing selenium.webdriver.remote.script_key
# cleanup[2] removing selenium.webdriver.common.by
# cleanup[2] removing selenium.webdriver.remote.shadowroot
# cleanup[2] removing selenium.webdriver.common.alert
# cleanup[2] removing selenium.webdriver.remote.webelement
# cleanup[2] removing selenium.webdriver.remote.switch_to
# cleanup[2] removing selenium.webdriver.common.proxy
# cleanup[2] removing selenium.webdriver.common.options
# cleanup[2] removing selenium.webdriver.common.print_page_options
# cleanup[2] removing selenium.webdriver.common.timeouts
# cleanup[2] removing selenium.webdriver.common.html5
# cleanup[2] removing selenium.webdriver.common.html5.application_cache
# cleanup[2] removing selenium.webdriver.support
# cleanup[2] removing selenium.webdriver.support.relative_locator
# cleanup[2] removing selenium.webdriver.remote.webdriver
# cleanup[2] removing signal
# cleanup[2] removing _posixsubprocess
# cleanup[2] removing subprocess
# cleanup[2] removing selenium.webdriver.firefox.firefox_binary
# cleanup[2] removing xml
# cleanup[2] removing xml.dom.domreg
# cleanup[2] removing xml.dom
# cleanup[2] removing xml.dom.minicompat
# cleanup[2] removing xml.dom.NodeFilter
# cleanup[2] removing xml.dom.xmlbuilder
# cleanup[2] removing xml.dom.minidom
# cleanup[2] removing selenium.webdriver.firefox.firefox_profile
# cleanup[2] removing selenium.webdriver.firefox.options
# cleanup[2] removing selenium.webdriver.firefox.remote_connection
# cleanup[2] removing selenium.webdriver.common.service
# cleanup[2] removing selenium.webdriver.firefox.service
# cleanup[2] removing selenium.webdriver.firefox.webdriver
# cleanup[2] removing selenium.webdriver.chrome
# cleanup[2] removing selenium.webdriver.chromium
# cleanup[2] removing selenium.webdriver.edge
# cleanup[2] removing selenium.webdriver.chromium.options
# cleanup[2] removing selenium.webdriver.edge.options
# cleanup[2] removing selenium.webdriver.chrome.options
# cleanup[2] removing selenium.webdriver.chromium.remote_connection
# cleanup[2] removing selenium.webdriver.chromium.webdriver
# cleanup[2] removing selenium.webdriver.chromium.service
# cleanup[2] removing selenium.webdriver.chrome.service
# cleanup[2] removing selenium.webdriver.chrome.webdriver
# cleanup[2] removing selenium.webdriver.ie
# cleanup[2] removing selenium.webdriver.ie.service
# cleanup[2] removing selenium.webdriver.ie.options
# cleanup[2] removing selenium.webdriver.ie.webdriver
# cleanup[2] removing selenium.webdriver.edge.service
# cleanup[2] removing selenium.webdriver.edge.webdriver
# cleanup[2] removing selenium.webdriver.opera
# cleanup[2] removing selenium.webdriver.opera.options
# cleanup[2] removing selenium.webdriver.opera.webdriver
# cleanup[2] removing selenium.webdriver.safari
# cleanup[2] removing selenium.webdriver.safari.options
# cleanup[2] removing selenium.webdriver.safari.service
# cleanup[2] removing selenium.webdriver.safari.remote_connection
# cleanup[2] removing selenium.webdriver.safari.webdriver
# cleanup[2] removing selenium.webdriver.webkitgtk
# cleanup[2] removing selenium.webdriver.webkitgtk.service
# cleanup[2] removing selenium.webdriver.webkitgtk.options
# cleanup[2] removing selenium.webdriver.webkitgtk.webdriver
# cleanup[2] removing selenium.webdriver.wpewebkit
# cleanup[2] removing selenium.webdriver.wpewebkit.service
# cleanup[2] removing selenium.webdriver.wpewebkit.webdriver
# cleanup[2] removing selenium.webdriver.wpewebkit.options
# cleanup[2] removing selenium.webdriver.common.actions
# cleanup[2] removing selenium.webdriver.common.actions.interaction
# cleanup[2] removing selenium.webdriver.common.actions.input_device
# cleanup[2] removing selenium.webdriver.common.actions.key_input
# cleanup[2] removing selenium.webdriver.common.actions.key_actions
# cleanup[2] removing selenium.webdriver.common.actions.mouse_button
# cleanup[2] removing selenium.webdriver.common.actions.pointer_input
# cleanup[2] removing selenium.webdriver.common.actions.pointer_actions
# cleanup[2] removing selenium.webdriver.common.actions.wheel_input
# cleanup[2] removing selenium.webdriver.common.actions.wheel_actions
# cleanup[2] removing selenium.webdriver.common.actions.action_builder
# cleanup[2] removing selenium.webdriver.common.action_chains
# cleanup[2] removing selenium.webdriver
# cleanup[2] removing selenium.webdriver.support.select
# cleanup[2] removing selenium.webdriver.support.wait
# cleanup[2] removing selenium.webdriver.support.ui
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing unicodedata
# cleanup[2] removing stringprep
# cleanup[2] removing encodings.idna
# destroy _queue
# destroy _sha3
# destroy _blake2
# destroy _datetime
# destroy _bz2
# destroy selenium.webdriver
# destroy selenium.webdriver.firefox
# destroy selenium.webdriver.firefox.firefox_binary
# destroy selenium.webdriver.firefox.firefox_profile
# destroy selenium.webdriver.firefox.options
# destroy selenium.webdriver.firefox.remote_connection
# destroy selenium.webdriver.firefox.service
# destroy selenium.webdriver.firefox.webdriver
# destroy selenium.webdriver.common
# destroy selenium.webdriver.common.desired_capabilities
# destroy selenium.webdriver.common.keys
# destroy selenium.webdriver.common.by
# destroy selenium.webdriver.common.alert
# destroy selenium.webdriver.common.proxy
# destroy selenium.webdriver.common.options
# destroy selenium.webdriver.common.print_page_options
# destroy selenium.webdriver.common.timeouts
# destroy selenium.webdriver.common.html5
# destroy selenium.webdriver.common.html5.application_cache
# destroy selenium.webdriver.common.actions
# destroy selenium.webdriver.common.actions.input_device
# destroy selenium.webdriver.common.actions.key_input
# destroy selenium.webdriver.common.actions.key_actions
# destroy selenium.webdriver.common.actions.mouse_button
# destroy selenium.webdriver.common.actions.pointer_input
# destroy selenium.webdriver.common.actions.pointer_actions
# destroy selenium.webdriver.common.actions.wheel_input
# destroy selenium.webdriver.common.actions.wheel_actions
# destroy selenium.webdriver.common.actions.action_builder
# destroy selenium.webdriver.common.action_chains
# destroy selenium.webdriver.remote
# destroy selenium.webdriver.remote.bidi_connection
# destroy selenium.webdriver.remote.command
# destroy selenium.webdriver.remote.errorhandler
# destroy selenium.webdriver.remote.file_detector
# destroy selenium.webdriver.remote.mobile
# destroy selenium.webdriver.remote.remote_connection
# destroy selenium.webdriver.remote.script_key
# destroy selenium.webdriver.remote.shadowroot
# destroy selenium.webdriver.remote.webelement
# destroy selenium.webdriver.remote.switch_to
# destroy selenium.webdriver.remote.webdriver
# destroy selenium.webdriver.support
# destroy selenium.webdriver.support.relative_locator
# destroy selenium.webdriver.support.select
# destroy selenium.webdriver.support.wait
# destroy selenium.webdriver.support.ui
# destroy selenium.webdriver.chrome
# destroy selenium.webdriver.chrome.options
# destroy selenium.webdriver.chrome.service
# destroy selenium.webdriver.chrome.webdriver
# destroy selenium.webdriver.chromium
# destroy selenium.webdriver.chromium.options
# destroy selenium.webdriver.chromium.remote_connection
# destroy selenium.webdriver.chromium.webdriver
# destroy selenium.webdriver.edge
# destroy selenium.webdriver.edge.options
# destroy selenium.webdriver.edge.service
# destroy selenium.webdriver.edge.webdriver
# destroy selenium.webdriver.ie
# destroy selenium.webdriver.ie.service
# destroy selenium.webdriver.ie.options
# destroy selenium.webdriver.ie.webdriver
# destroy selenium.webdriver.opera
# destroy selenium.webdriver.opera.options
# destroy selenium.webdriver.opera.webdriver
# destroy selenium.webdriver.safari
# destroy selenium.webdriver.safari.options
# destroy selenium.webdriver.safari.service
# destroy selenium.webdriver.safari.remote_connection
# destroy selenium.webdriver.safari.webdriver
# destroy selenium.webdriver.webkitgtk
# destroy selenium.webdriver.webkitgtk.service
# destroy selenium.webdriver.webkitgtk.options
# destroy selenium.webdriver.webkitgtk.webdriver
# destroy selenium.webdriver.wpewebkit
# destroy selenium.webdriver.wpewebkit.service
# destroy selenium.webdriver.wpewebkit.webdriver
# destroy selenium.webdriver.wpewebkit.options
# destroy _sitebuiltins
# destroy _struct
# destroy _compression
# destroy _lzma
# destroy pwd
# destroy grp
# destroy struct
# destroy bz2
# destroy lzma
# destroy importlib.util
# destroy importlib.resources
# destroy importlib.machinery
# destroy importlib
# destroy zipimport
# destroy _socket
# destroy string
# destroy certifi
# destroy certifi.core
# destroy urllib3
# destroy platform
# destroy selenium.webdriver.remote.utils
# destroy importlib.abc
# destroy fnmatch
# destroy urllib.parse
# destroy ntpath
# destroy urllib3.packages
# destroy urllib3.exceptions
# destroy urllib3._version
# destroy urllib3.contrib
# destroy urllib3.util
# destroy urllib3.util.wait
# destroy urllib3.util.request
# destroy urllib3.util.response
# destroy urllib3.util.retry
# destroy urllib3.util.url
# destroy urllib3.util.ssltransport
# destroy urllib3.util.ssl_
# destroy urllib3.util.timeout
# destroy urllib3.util.proxy
# destroy urllib3.util.ssl_match_hostname
# destroy urllib3.util.queue
# destroy urllib3._collections
# destroy urllib3.connection
# destroy urllib3.fields
# destroy urllib3.filepost
# destroy urllib3.request
# destroy urllib3.response
# destroy urllib3.connectionpool
# destroy urllib3.poolmanager
# destroy operator
# destroy types
# destroy urllib3.packages.six.moves
# destroy urllib3.packages.six.moves.urllib
# destroy urllib3.packages.six.moves.urllib_parse
# destroy urllib3.packages.six.moves.urllib.error
# destroy urllib3.packages.six.moves.urllib.request
# destroy urllib3.packages.six.moves.urllib.response
# destroy urllib3.packages.six.moves.urllib.robotparser
# destroy http
# destroy email.quoprimime
# destroy email.base64mime
# destroy email.encoders
# destroy email._parseaddr
# destroy email._policybase
# destroy email.feedparser
# destroy email.parser
# destroy email._encoded_words
# destroy email.iterators
# destroy email.message
# destroy email.header
# destroy random
# destroy calendar
# destroy locale
# destroy encodings
# destroy uu
# destroy quopri
# destroy email.utils
# destroy email.charset
# destroy email.errors
# destroy _ssl
# destroy datetime
# destroy urllib3.util.connection
# destroy urllib3.contrib._appengine_environ
# destroy hmac
# destroy hashlib
# destroy socket
# destroy ssl
# destroy ipaddress
# destroy binascii
# destroy email
# destroy mimetypes
# destroy urllib
# destroy zlib
# destroy queue
# destroy logging
# destroy urllib3.packages.six
# destroy json.decoder
# destroy json.encoder
# destroy json.scanner
# destroy _json
# destroy _uuid
# destroy _hashlib
# destroy pkgutil
# destroy signal
# destroy contextlib
# destroy select
# destroy selectors
# destroy _signal
# destroy _posixsubprocess
# destroy json
# destroy shutil
# destroy tempfile
# destroy zipfile
# destroy xml.dom
# destroy xml.dom.minicompat
# destroy xml.dom.NodeFilter
# destroy xml.dom.xmlbuilder
# destroy xml.dom.minidom
# destroy xml.dom.domreg
# destroy copy
# destroy xml
# destroy errno
# destroy subprocess
# destroy base64
# destroy selenium.webdriver.chromium.service
# destroy selenium.webdriver.common.utils
# destroy http.client
# destroy selenium.webdriver.common.service
# destroy uuid
# destroy selenium.webdriver.common.actions.interaction
# destroy unicodedata
# cleanup[3] wiping encodings.idna
# destroy stringprep
# cleanup[3] wiping _random
# cleanup[3] wiping _sha512
# cleanup[3] wiping _bisect
# cleanup[3] wiping atexit
# cleanup[3] wiping _string
# cleanup[3] wiping traceback
# destroy linecache
# cleanup[3] wiping tokenize
# cleanup[3] wiping math
# cleanup[3] wiping weakref
# cleanup[3] wiping importlib._bootstrap_external
# cleanup[3] wiping importlib._bootstrap
# destroy _frozen_importlib_external
# cleanup[3] wiping collections.abc
# cleanup[3] wiping threading
# cleanup[3] wiping warnings
# cleanup[3] wiping re
# destroy enum
# destroy sre_compile
# destroy copyreg
# cleanup[3] wiping _locale
# destroy _locale
# cleanup[3] wiping functools
# cleanup[3] wiping _functools
# destroy _functools
# cleanup[3] wiping collections
# destroy _collections_abc
# destroy heapq
# destroy collections.abc
# cleanup[3] wiping _collections
# destroy _collections
# cleanup[3] wiping itertools
# destroy itertools
# cleanup[3] wiping _heapq
# cleanup[3] wiping _operator
# destroy _operator
# cleanup[3] wiping sre_parse
# cleanup[3] wiping _sre
# cleanup[3] wiping os
# destroy posixpath
# cleanup[3] wiping genericpath
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping io
# destroy abc
# cleanup[3] wiping _abc
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.cp437
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping time
# cleanup[3] wiping _weakref
# cleanup[3] wiping _thread
# cleanup[3] wiping posix
# cleanup[3] wiping marshal
# destroy marshal
# cleanup[3] wiping _io
# destroy io
# cleanup[3] wiping _warnings
# cleanup[3] wiping _imp
# destroy _imp
# cleanup[3] wiping _frozen_importlib
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy stat
# destroy genericpath
# destroy _sre
# destroy sre_parse
# destroy functools
# destroy tokenize
# destroy _heapq
# destroy _frozen_importlib
# clear sys.audit hooks

**Comment by jonkpirateboy** [comment]
Om du kollar på sidan så står det inte "kungsbacka" utan "Kungsbacka", det är viktigt att man skriver exakt samma.
