### ISSUE TITLE
Possible way to book for multiple persons?

### ISSUE THREAD

**Issue by fredentoft** [jonkpirateboy/Pass-fur-alle#10]
add variable
```
numberOfPeople = 4
```
On "accept-screen"
```
        Select(web.find_element(by=By.XPATH, value='//*[@id="NumberOfPeople"]')).select_by_visible_text(str(numberOfPeople))
```
change radiobutton behaviour
```
        liveInRadios = web.find_elements(by=By.XPATH, value="//input[@type='radio'][@value='2']")
        for liveInRadio in liveInRadios:
          liveInRadio.click()
```

**Comment by fracii** [comment]
How do all your section
# Confirm living in Sweden 

look like?

I get   

File "pass-fur-alle.py", line 68
    liveInRadio.click()
    ^
IndentationError: expected an indented block

**Comment by fredentoft** [comment]
With my edit you mean?
that line has to be indentet 2 spaces from the "for " statement

**Comment by fracii** [comment]
> With my edit you mean?
> that line has to be indentet 2 spaces from the "for " statement

Yes How do all your code look like?

**Comment by fredentoft** [comment]
I just replaced the lines containing liveInRadio with the code i pasted here

What also needs to be adressed is adding names of the other persons i tha later stages when at time is found.

However, as most available times are cancellations the odds of getting a "multiperson" booking are probably slim.

**Comment by johanbrook** [comment]
I did like this: https://github.com/jonkpirateboy/Pass-fur-alle/pull/2

**Comment by jonkpirateboy** [comment]
Fixed in latest version released today
