### ISSUE TITLE
Captcha stoppar scriptet

### ISSUE THREAD

**Issue by KianBrose** [jonkpirateboy/Pass-fur-alle#105]
![image](https://user-images.githubusercontent.com/62078964/168420825-09b84ecb-08e4-4ed5-8cfb-e00430a7a155.png)

They're destroying their own website to destroy pass fur alle

Maybe captcha solve service can do the job?

Note: It seems to disappear for a while after solving it once, unsure for how long

**Comment by jonkpirateboy** [comment]
Ok, an update has been made. The user has to fill the captcha but is notified by a crash sound and the search box is closed.
