### ISSUE TITLE
Issues after latest update on the site for booking time for passport

### ISSUE THREAD

**Issue by raadab** [jonkpirateboy/Pass-fur-alle#108]
Version 2.16
1. After login in, the personal number and name are directly shown now. It was previously shown just after a timeslot is found and the user wants to book it. Thus the sound  for the succeeded in finding a timeslot is played now directly after login when it was played just after finding a time.
2. When the script finds a time no sound is played and the time found is not displayed until you fill your email and your phone number,  prbably due to changes made on the steps for booking time on the booking system.

However, the script is still able to find pass time 👍 👍 🥇

**Comment by jonkpirateboy** [comment]
Fixed in 2.17. Thanks for the heads up!
