### ISSUE TITLE
Cant search earlier then 21-06-2022

### ISSUE THREAD

**Issue by shsh1801** [jonkpirateboy/Pass-fur-alle#109]
Hi,

Im trying to find a time this week for my friend but the system is giving me error message saying I can not search for a time earlier then 21-06-2022... Is there anyway to fix this?

**Comment by inspectadeck** [comment]
You can change the date under // Constants

By default, the script will search from today. See below. 
var dateFrom = today();

If you want to start some other day, just change this to a date with the format YYYY-MM-DD, for example:

var dateFrom = '2022-08-24';

**Comment by jonkpirateboy** [comment]
> Hi,
> 
> Im trying to find a time this week for my friend but the system is giving me error message saying I can not search for a time earlier then 21-06-2022... Is there anyway to fix this?

No, that's a part of the booking system. We can't bypass their backend limitations.
