### ISSUE TITLE
reCAPTCHA pops up and cancells the search

### ISSUE THREAD

**Issue by riverrm** [jonkpirateboy/Pass-fur-alle#110]
"Crashes" the search with a broken glass sound.... need to type in the letters, then reactivate the search. Random time, but 3-10 minutes and it will come up.

Any walk arounds?

**Comment by jonkpirateboy** [comment]
No, the crash sound is a part of Pass für alle to make it easier to notice that the search stopped for captcha. This is something we can not bypass I think. But maybe there is an auto captcha solver out there that we can include. I haven't found one yet.
