### ISSUE TITLE
Uncaught TypeError when running a search

### ISSUE THREAD

**Issue by pettermahlen** [jonkpirateboy/Pass-fur-alle#111]
```
init.js:30 Uncaught TypeError: $(...).datepicker is not a function
    at init.js:30:22
    at dispatch (jquery?v=qWq_uEaMDsyjxUIrGMHmmh4Hs1ha7TuAcFmRMIvZ4O81:1:55286)
    at y.handle (jquery?v=qWq_uEaMDsyjxUIrGMHmmh4Hs1ha7TuAcFmRMIvZ4O81:1:52032)
```

I get the feeling that the search is stuck ("Söker efter tid.../Avbryt"), but maybe it's just taking time.

**Comment by pettermahlen** [comment]
I don't see any network activity, so I guess it's pretty definite that the search is stuck?

**Comment by jonkpirateboy** [comment]
This is an error with the booking system itself that does not affect Pass für alle.

**Comment by pettermahlen** [comment]
OK - but would you expect to see zero network activity while the search is ongoing? I would have expected to see lots of requests back and forth. It looks to me like the search is stalled, even though the spinner says that it's searching.
