### ISSUE TITLE
Län and Expedition 

### ISSUE THREAD

**Issue by drifton** [jonkpirateboy/Pass-fur-alle#14]
Hi, 
I can't get It to work when it comes for me to select län and expedition..
In terminal I type Län: Skåne and Expedition: Lund, but I get error page in Google Chrome.

Anyone else having the same issue?

**Comment by jonkpirateboy** [comment]
Read the instruction: "Välj län. Sista delen av url t ex 'halland'. Eller tryck enter för Skåne: ", so it should be skane. All the URLs can be found here, https://polisen.se/tjanster-tillstand/pass-och-nationellt-id-kort/boka-tid-hitta-passexpedition/, as stated in the terminal too. Good luck! :)
