### ISSUE TITLE
Får det att köra, men hur ändrar jag i scriptet till rätt uppgifter, Kan inte detta alls, men jag har ju lyckats köra det.

### ISSUE THREAD

**Issue by erodab** [jonkpirateboy/Pass-fur-alle#15]

**Comment by cakism** [comment]
När du laddat ner scriptet, öppna filen pass-fur-alle.py i en texteditor - obs inte Word eller dylikt utan t.ex. notepad. Nästan högst upp i filen ser du fälten som du kan ändra till dina egna uppgifter. Spara filen när du ändrat och sen kör du scriptet igen.

**Comment by jonkpirateboy** [comment]
What @cakism said :)
