### ISSUE TITLE
Selecting "Expedition" doesn't seem to work

### ISSUE THREAD

**Issue by ZtefanS** [jonkpirateboy/Pass-fur-alle#17]
First, nice script, thanks!

Tried to use it to book at specific "Expedition" but that fails because the available times are presented weekly for a single "Expedition" rather than by "Expidition" as it does when you search for all Expeditions. The script terminates.

**Comment by jonkpirateboy** [comment]
Have you spelled it right and checked that your choice actually is an option?

**Comment by jonkpirateboy** [comment]
Just tested with:
Län:  stockholm
Expedition:  Nacka
and it works like a charm!

**Comment by ZtefanS** [comment]
yepp, spelled right. Wierd it doesn't work for me. No big problem though.

Thanks!
