### ISSUE TITLE
För många anrop, skickad till reservwebbplats

### ISSUE THREAD

**Issue by herrgiden** [jonkpirateboy/Pass-fur-alle#20]
Hej, jag får resultatet "du har gjort för många anrop till polisen.se under en kort tid. Har jag gjort något tokigt? Har tre personer, mina barn, jag försöker söka för.

**Comment by matteh80** [comment]
De har börjat kolla om chrome styrs av testmjukvara, det är därför.

**Comment by geekteq** [comment]
Tror att det är att "selenium" jobbar för snabbt, de har helt sonika lagt in en avkänning som gör att "robotarna" (vi) inte kan agera för snabbt.. nån idé om hur man kan sakta ner scriptet lite och testa?

**Comment by JiviYak** [comment]
> > De har börjat kolla om chrome styrs av testmjukvara, det är därför.
> 
> jaha, vad kan man göra åt det då tro?

Det funkade för mig att ta bort Navigator.Webdriver flaggan. Gör så att chrome inte ser att selenium används.

Ersätt 
`web = webdriver.Chrome()`
Med
`option = webdriver.ChromeOptions()

#Removes navigator.webdriver flag

# For older ChromeDriver under version 79.0.3945.16
# option.add_experimental_option("excludeSwitches", ["enable-automation"])
# option.add_experimental_option('useAutomationExtension', False)

#For ChromeDriver version 79.0.3945.16 or over
option.add_argument('--disable-blink-features=AutomationControlled')

#Open Browser
web = webdriver.Chrome(executable_path='/usr/lib/chromium-browser/chromedriver',options=option)`

Glöm inte ändra path till chromedriver om ni har det på annan plats, eller att lägga till .exe om det är windows

**Comment by jonkpirateboy** [comment]
Uppdatera till senaste versionen
