### ISSUE TITLE
https://reserv.polisen.se/for-manga-anrop/

### ISSUE THREAD

**Issue by mickepop** [jonkpirateboy/Pass-fur-alle#21]
Hej, 
När jag kör skriptet så hamnar jag på: https://reserv.polisen.se/for-manga-anrop/
Några tips?

**Comment by Sten-Frisk** [comment]
Installera [Tunnelbear](https://www.tunnelbear.com/) eller någon annan smidig proxy att använda i webbläsaren. Borde hjälpa för stunden.

**Comment by antonhedling** [comment]
Ser ut som att dom kollar efter `webdriver` i requesten numera (?), för jag får detta nu också trots att jag inte blir blockerad om jag går manuellt. Googlade mig runt lite och det fungerade för mig att lägga till detta direkt under `web = webdriver.Chrome()`, rad 13. Dvs så att det ser ut såhär:

```
web = webdriver.Chrome()
web.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
    "source":
        "const newProto = navigator.__proto__;"
        "delete newProto.webdriver;"
        "navigator.__proto__ = newProto;"
    })
```

**Comment by jonkpirateboy** [comment]
Uppdatera till senaste versionen
