### ISSUE TITLE
Website error "too many calls".

### ISSUE THREAD

**Issue by Anvnamnet** [jonkpirateboy/Pass-fur-alle#24]
After running it for a couple of hours and then restarting the script, I got the website error about me calling on the website too much.
Is there a way to bypass this? Rerouting through proxy? Or is that going to block me since proxies can be a bit sus to some websites?

I have reset browser, started a new VMbox session to no avail.
Even tried on Ubuntu instead of Kali. No result. Still same error. 

I know they were going to implement some kind of bot protection. But how do we bypass this? I do really need my passsport! XD

**Comment by herrgiden** [comment]
This was closed in a previous issue. Check "closed" issues. Script has been updated.

**Comment by Anvnamnet** [comment]
Sorry
