### ISSUE TITLE
Kod Problem?

### ISSUE THREAD

**Issue by jlivingstonsg** [jonkpirateboy/Pass-fur-alle#25]
Hej.

Testade installationsfilen för 
VcXsrv Windows X Server / Windows
för virus och fick lite varningar här.
https://www.virustotal.com/
Ska man bry sig?

Magnus

**Comment by jonkpirateboy** [comment]
@larsmjoh?

**Comment by larsmjoh** [comment]
It passed McAffe om my machine...

**Comment by jlivingstonsg** [comment]
Det är 1 april snart  så jag bara dubbelkollar allt nu.  :)

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
