### ISSUE TITLE
Recursion in the script will cause crash if script is ran for too long

### ISSUE THREAD

**Issue by tistatos** [jonkpirateboy/Pass-fur-alle#27]
If the script is allowed to run for a long period of time, it will eventually crash with a RecursionError.

Is there a reason for the recursive solution? otherwise it should be easy to convert the solution to a while loop.

**Comment by jonkpirateboy** [comment]
I've set the recursion to 10000 to avoid putting pressure on the booking site. How long dit it take for you to get a RecursionError? I have not seen or heard of any problems as of now.

**Comment by tistatos** [comment]
I don't see what the recursion has to do with pressure on the site? But I guess the time it takes to hit the limit on recursion is a function of the date range you're searching in and how long the session is valid.

my date range was 123 days and I hit the cap after about 48h of running

**Comment by tomasskare** [comment]
I've also seen this. The problem is that both searchPassTime() and clickTimeIfExists() call themselves at the end to "start over", instead of having loops in the functions. Since neither function actually return, it will just fill the stack and eventually cause the recursion error (or Python crashing).

**Comment by tedpelas** [comment]
Here is the [Traceback log](https://github.com/jonkpirateboy/Pass-fur-alle/files/8387424/maximum_recursion_dept_exceeded.log) from the `RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by tedpelas** [comment]
```
RecursionError: maximum recursion depth exceeded while calling a Python object
START: Sun Apr 3 17:08:38 CEST 2022,
END: Mon Apr 4 03:21:08 CEST 2022
```

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
