### ISSUE TITLE
WSL kan inte hitta den nedladdade filen chromedriver

### ISSUE THREAD

**Issue by Jonatpe** [jonkpirateboy/Pass-fur-alle#29]
Laddade ner rätt version av chromedriver, men när jag försöker fortsätta med commandot i windows hjälpen å hittas inte chromedriver av terminalen. Vad är det för fel? jag har extractat filen in min downloads (även kallad hämtade filer). Har testat både:
sudo mv -f ~/Downloads/chromedriver /usr/local/share/
och
sudo mv -f ~/Hämtade-filer/chromedriver /usr/local/share/

men får 
mv: cannot stat '/root/chromedriver': No such file or directory
vad jag än testar

**Comment by mellonnen** [comment]
WSL filsystem är lite knepigt att förstå då du egentligen måste hålla koll på ett linux filsystem och ditt windows filsystem.

 Du kan komma åt dina nedladdade "windows"  filer från WSL (linux) via `/mnt/c/Users/<din-windows-användare>/Downloads`  

Alternativt can du följa den här [steg-för-steg guiden](https://cloudbytes.dev/snippets/run-selenium-and-chrome-on-wsl2#step-2-install-latest-chrome-for-linux) för att sätta up selenium för WSL. Gör alla steg upp til steg 4, sedan kan du följa instruktionerna i detta repo. Är en del kommandon, men om man tar det steg för steg så blir det lite enklare.

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
