### ISSUE TITLE
How do I change the script for people not living in Sweden?

### ISSUE THREAD

**Issue by tictactoes** [jonkpirateboy/Pass-fur-alle#31]
Like the title said. For Swedish citizens not resident in Sweden.

**Comment by jonkpirateboy** [comment]
Change:
liveInRadio = web.find_element(by=By.XPATH, value='//*[@id="Main"]/form/div[1]/div[%s]/div/label[1]' % divCount)
To:
liveInRadio = web.find_element(by=By.XPATH, value='//*[@id="Main"]/form/div[1]/div/div/label[2]' % divCount)

Not tested.

**Comment by tictactoes** [comment]
This results in:

`  File "pass-fur-alle.py", line 75, in searchPassTime
    liveInRadio = web.find_element(by=By.XPATH, value='//[@id="Main"]/form/div[1]/div/div/label[2]' % divCount)
TypeError: not all arguments converted during string formatting`
