### ISSUE TITLE
I get redirected to reserv.polisen.se

### ISSUE THREAD

**Issue by svewes** [jonkpirateboy/Pass-fur-alle#34]
When running the script I get redirected to reserv.polisen.se.
And get the message: 

För många anrop
Du har gjort för många anrop till polisen.se under en kort tid. Ditt besök har dirigerats till vår reservwebbplats.

Any solution to this?

BR
Sven

**Comment by TherisaHaze** [comment]
De verkar ha blockerat Chromium.

**Comment by jonkpirateboy** [comment]
Upgrade to latast version. Duplicate of #20 #21 #22 #23 #24. Please search before posting.

**Comment by svewes** [comment]
Ok, thanks for the reply. (Sorry for not checking properly, I am new to Github. ) :-)
