### ISSUE TITLE
the developer cannot be verified??

### ISSUE THREAD

**Issue by tjenatjena12** [jonkpirateboy/Pass-fur-alle#35]
Received the error:

“chromedriver” cannot be opened because the developer cannot be verified.

macOS cannot verify that this app is free from malware.

How can I go around this?

**Comment by jonkpirateboy** [comment]
Right click on chromedriver where it is installed and open it. There you can allow it to be opened.

**Comment by tjenatjena12** [comment]
Thanks. I've reopened it as instructed "ChromeDriver was started successfully." and I am still receiving the same message. 

“chromedriver” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.


What should I do?
