### ISSUE TITLE
I'm getting an error message when installing Selenium

### ISSUE THREAD

**Issue by MartinHolmSWE** [jonkpirateboy/Pass-fur-alle#36]
Hi
I'm getting an error message when installing Selenium... Does anyone have any idea why I get this? "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5ihwbgpi/cryptography/"
Here is the whole output (where the error-message is):
"
Using cached https://files.pythonhosted.org/packages/10/a7/51953e73828deef2b58ba1604de9167843ee9cd4185d8aaffcb45dd1932d/cryptography-36.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5ihwbgpi/cryptography/setup.py", line 84
        print(f"    Python: {'.'.join(str(v) for v in sys.version_info[:3])}")
^
    SyntaxError: invalid syntax
"
_the ^ is under the "-mark in " ... version_info[:3])}") "_
I also get a warning about using an older version of pip ("pip version 8.1.1"), might that be causing this error?

**Comment by MartinHolmSWE** [comment]
Using Linux, Ubuntu 16.04 LTS

**Comment by tedpelas** [comment]
Try updating your environment first, pip version 22.0.4 is the latest

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
