### ISSUE TITLE
MacOS: "ImportError: No module named selenium.webdriver.common.keys"

### ISSUE THREAD

**Issue by jorgenen** [jonkpirateboy/Pass-fur-alle#37]
MacOS:
Have followed the instructions and installed everything as described. When running the script I get "ImportError: No module named selenium.webdriver.common.keys". Would be very grateful for any pointers to what this indicates/how to fix.

**Comment by simonmahdavi** [comment]
I had the same issue! It is probably related to you security and integrity settings on Mac! I allowed the chromedriver in the settings! And it worked for me after that!!
