### ISSUE TITLE
When using firstDate = true, after some time a time is booked way after endBookingDate

### ISSUE THREAD

**Issue by henhal** [jonkpirateboy/Pass-fur-alle#38]
Using

```
startBookingDate = "2022-03-31"
endBookingDate = "2022-08-15"
firstDate = True
```

This runs for a while, and then suddenly I get a time booked for 2022-11-09. This has happened three times. It seems like after a while, the first available time is booked regardless of the `endBookingDate` condition.
I haven't managed to understand why `if formInputDateTime > endBookingDateDateTime` is suddenly false for `2022-11-09 > 2022-08-15`, the only explanation I can think of is that `formInputDateTime` is incorrectly parsed into an empty string or something like that?

**Comment by jonkpirateboy** [comment]
Just tested, it does not. At least not with the latest version. This is run regardless of using firstDate True or False:
if (manualVerify == False):
                # Verify your booking
                web.find_element(by=By.XPATH, value='//*[@id="Main"]/form/div[1]/input').click()

**Comment by henhal** [comment]
I'm not saying it happens on every iteration, it ran for 5-10 minutes and in all three runs it ended up suddenly booking 2022-11-09. So it's not really deterministic. I can add some debug prints and try again.
Anyway I got my time tomorrow now so I'm happy. ❤️

**Comment by jonkpirateboy** [comment]
Do that. And also, don't forget to unbook unwanted bookings.

**Comment by TheaHunter** [comment]
Have the same issue. :)

**Comment by jonkpirateboy** [comment]
I tried, but I can't seem to reproduce the error. Ran for 30 minutes and no cigar.

**Comment by henhal** [comment]
I can't _try_ to reproduce it because I've hit the traffic limit at polisen.se for my IP yesterday and I'm still not allowed to access it. 
Is this a new limitation they've added to combat the script? 

I don't have time to fiddle with VPN to try this from another IP right now, but great that you couldn't reproduce it. 🤷
