### ISSUE TITLE
Ny "låsning"? Telefonnummer får varning om att inte var korrekt

### ISSUE THREAD

**Issue by geekteq** [jonkpirateboy/Pass-fur-alle#39]
Jag får telefonnummer är inte korrekt när jag kör automatik. Kör copy&paste manuellt ger samma resultat. När jag matar inte det manuellt så går det igenom (exakt samma nummer).

Kanske en ny version av att de försöker blockera scriptet? Händer inte alltid utan intermittent.

Bara för info & kanske en varning att de jobbar på nåt med det så stäng "issuen" när/om du vill ;)

**Comment by jonkpirateboy** [comment]
Hur har du skrivit in ditt telefonnummer?

**Comment by geekteq** [comment]
Exempel: '072x48x38x‬'
När jag kom till bekräftelsen klagade bokningssystemet.
Jag tog numret igen och copy&pasted - funkade inte.
Skrev in det två gånger manuellt med samma innehåll - pling, klart.

**Comment by jonkpirateboy** [comment]
Mycket märkligt, har aldrig sett felet. Det kanske hängde med nåt osynligt [obj] eller så när du klistrade in.

**Comment by geekteq** [comment]
Inte omöjligt - kikade men såg inga, men skit händer.
