### ISSUE TITLE
är inte jättebra på att coda så vet inte riktitg hur jag ska starta själva koden

### ISSUE THREAD

**Issue by Jahamez88** [jonkpirateboy/Pass-fur-alle#43]
ska jag bara slänga in den i Python och trycka enter eller missar jag nått steg? 

när jag trycker enter i phython så kommer det här upp

![image](https://user-images.githubusercontent.com/102751979/161104338-d085e942-7bb6-4861-ab12-34fd828436a2.png)

hjälp snälla 

Svenska

**Comment by d00ze** [comment]
Scriptet fungerar inte längre då hemsidan för pass-bokning är ombyggd med högresäkerhet och tids-spärr om man försöker söka tider för fort.
