### ISSUE TITLE
Update Chrome Browser and Chrome-driver to "same version"

### ISSUE THREAD

**Issue by Leopenardo** [jonkpirateboy/Pass-fur-alle#45]
![image](https://user-images.githubusercontent.com/102758235/161119653-14d498f2-0b38-4a62-a094-2f62bf636ee4.png)

I do not get it.. Can someone please explain how to solve this problem? Thank u! :)

**Comment by d00ze** [comment]
Try run a VM Virtualbox and install Ubuntu on that and then run the Python Script insted of following the Windows guide.

**Comment by Leopenardo** [comment]
Thank u will do that directly!!

Can I ask when u activated the script? Was it yesterday or a week ago? I mean I hope it is still possible!

**Comment by mryner228** [comment]
Update your version of chrome would solve it? It says you have v99 and Chromedriver needs v100

**Comment by Leopenardo** [comment]
> Update your version of chrome would solve it? It says you have v99 and Chromedriver needs v100

But where? I have searched for chrome latest version on google but it do only download same trash version ... :(

**Comment by mryner228** [comment]
I'm on Mac and v100 seem to be the latest. Not sure why a v100 would be needed on windows. I updated mine just through settings in chrome. It's under 'about chrome' in settings

**Comment by Leopenardo** [comment]
WTF! It says version 100.0.4 in chrome but maybe I need to restart pc?

**Comment by mryner228** [comment]
That might be a good idea. Hope it works.

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
