### ISSUE TITLE
Have someone made it work?

### ISSUE THREAD

**Issue by jefferyjordan2** [jonkpirateboy/Pass-fur-alle#49]
I have tried all tools on github but non work.. Have someone made a script that works or a bot or something I will travel soon and really need all help I can get, thanks!

**Comment by jefferyjordan2** [comment]
I have tried all tools on github but non work.. Have someone made a script that works or a bot or something I will travel soon and really need all help I can get, thanks!

**Comment by tedpelas** [comment]
It works, you just need to monitor it closely, so it doesn't idle for a few hours.
But also that you need to confirm your booking once a slot is available, I added a Telegram notice for myself, but you could also let the script book it automatically.

Worst case you can use this: https://polisen.se/tjanster-tillstand/pass-och-nationellt-id-kort/provisoriskt-pass/

**Comment by jonkpirateboy** [comment]
See #42
