### ISSUE TITLE
NameError: name 'driver' is not defined

### ISSUE THREAD

**Issue by danwie** [jonkpirateboy/Pass-fur-alle#53]
Jag har problem med att klicka på den första knappen "Boka tid". Får felmeddelandet "NameError: name 'driver' is not defined". Enligt vad jag googlat mig till så kan detta bero på en bugg i Selenium, vilket man kan lösa genom att nedgradera <= 4. Alternativt kan man uppgradera sin chromedriver.

Har även testat:
WebDriverWait(web,20).until(EC.element_to_be_clickable((By.XPATH,'//*[@class="btn btn-primary btn-large disable-on-save"]'))).click()
Men får då ett liknande fel.

Nu tror jag att jag har de senaste versionerna av både selenium och chromedriver - så jag är lite osäker på hur jag går vidare. Ingen annan som har detta problem? Jag har kört brew upgrade och har försökt komma vidare på alla möjliga sätt. Men får ändå samma fel. Någon som har tips på hur jag kommer vidare? Kanske har jag en för gammal dator? Använder macOS High Sierra 10.13.6 på iMac från 2010...

**Comment by JohnKesko** [comment]
Inspektera "boka ny tid" elementet så ser du att de har lagt till "x" på slutet i large button.

**Comment by danwie** [comment]
> Inspektera "boka ny tid" elementet så ser du att de har lagt till "x" på slutet i large button.

Mm jag såg det. Har lagt in det, men det löser inte mitt problem tyvärr

**Comment by JohnKesko** [comment]
> > Inspektera "boka ny tid" elementet så ser du att de har lagt till "x" på slutet i large button.
> 
> Mm jag såg det. Har lagt in det, men det löser inte mitt problem tyvärr

Efter jag körde brew install --cask chromedriver fick jag till drivern till slut, kan va värt att prova.

**Comment by danwie** [comment]
Tack snälla för hjälpen. Nu fungerar det.

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
