### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by bjornet** [jonkpirateboy/Pass-fur-alle#55]
```python
def handleReCAPTCHA():
    try:
        web.execute_script("""
            document.querySelector('.mtcaptcha.controls').remove();
        """)
    except NoSuchElementException:
        pass
```

This banal solution worked for me @jonkpirateboy sry for not creating a PR but did not have time yet.

**Comment by jonkpirateboy** [comment]
Where do you call handleReCAPTCHA?

**Comment by bjornet** [comment]
It would be before or after the enumeration of people “selectAmountOfPeople”
