### ISSUE TITLE
Issue running in WSL

### ISSUE THREAD

**Issue by Tjawkis** [jonkpirateboy/Pass-fur-alle#6]
I followed you guide for Windows but got this error, any ideas?

```
:/mnt/c/temp/passfuralle$ python3 pass-fur-alle.py
Traceback (most recent call last):
  File "pass-fur-alle.py", line 12, in <module>
    web = webdriver.Chrome()
  File "/home/gustav/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/gustav/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/gustav/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/gustav/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1
```

**Comment by Tunnis3** [comment]
Got the same issue. What I did was instead of installing web driver via apt-get I installed it manually by downloading the latest version from [chromedriver.storage.googleapis.com](https://chromedriver.storage.googleapis.com/index.html)

**Comment by jonkpirateboy** [comment]
Was this on MacOS or Linux?

**Comment by Tunnis3** [comment]
This was on WSL2. You can run apt-get on WSL

**Comment by larsmjoh** [comment]
It seems the apt-package for chromedriver is just a wrapper around a snap. 
Since snapd is a bit of a hassle to get working under WSL I must admit I installed it manually (should add that to the WSL instruction)

**Comment by danhir** [comment]
The same error message is seen on WSL2 and when running on remote Linux servers with only console access. (No GUI)
The solution is to run the script in "headless" mode. The "manualVerify" option needs to be set to False.

Add these options to the main file:

from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
web = webdriver.Chrome(chrome_options=chrome_options)

**Comment by larsmjoh** [comment]
Depending on how you set up your WSL, the resolve.conf-grep may not work and you may have to figure out the correct ip-adress for you windows host. If you are running remote, you of course need to set a correct DISPLAY env.
@danhir I have a PR for exactly that: #5 Needs testing on bare-metal linux and MacOS...

**Comment by trasher64** [comment]
> Got the same issue. What I did was instead of installing chromedriver via apt-get I installed it manually by downloading the latest version from [chromedriver.storage.googleapis.com](https://chromedriver.storage.googleapis.com/index.html)

This worked for me too. Gotta make sure the new install is proper in your path too though, I just manually installed it in my homedir which didn't really work well until I fixed the path!

So after manual install try:
chromedriver --version
If you see the version, all good! If you still get an error suggesting to use snap for installing, fix your path.

**Comment by herrgiden** [comment]
I did not get this to work on WSL, I ended up using homebrew on my wife's Macbook instead.

**Comment by jewljewl** [comment]
I'm getting this error using WSL. Anyone have any ideas? 

`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "pass-fur-alle.py", line 16, in <module>
    web = webdriver.Chrome(options=options)
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/jewljewl/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55f6699bc7e9 <unknown>
`

**Comment by Tjawkis** [comment]
> I did not get this to work on WSL, I ended up using homebrew on my wife's Macbook instead.

Same for me, i ended up running Ubuntu live usb 20.04. I got issues with the version of the chromedriver and got it working using webdriver-manager - https://pypi.org/project/webdriver-manager/

**Comment by jonkpirateboy** [comment]
This is now closed since Pass für alle has changed from Python to Javascript
