### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by Anxinwonderland** [jonkpirateboy/Pass-fur-alle#62]
Även med det nya cookie-tillägget får jag felmeddelande:

Sidan fungerar inte
bokapass.nemoq.se omdirigerade dig för många gånger.
[Testa att rensa cookies]
(https://support.google.com/chrome?p=rl_error&hl=sv).

ERR_TOO_MANY_REDIRECTS

Har såklart rensat cookies. 
Någon som har fått det att fungera?

**Comment by j1MP** [comment]
Det fungerade imorse men sedan fick jag automatiska uppdateringar på datorn och den startades om. Nu när jag ska försöka hitta en ny tid så får jag precis som du, "Too many redirects". Teknikerna är snabba där borta?

**Comment by Anxinwonderland** [comment]
Ja, de verkar ha fullt upp med att se till att alla som behöver pass ska sitta och leta manuellt i dagar...

**Comment by 08Weber** [comment]
jag får upp felmedelandet "The page isn’t redirecting properly
An error occurred during a connection to bokapass.nemoq.se.
This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by 08Weber** [comment]
kör på linux med fire fox

**Comment by j1MP** [comment]
Jag har testat med linux chrome/firefox. Även med windows chrome, samma fel.

**Comment by jonkpirateboy** [comment]
Funkar inte längre pga uppdatering i deras kod. Så detta felet är förväntat.

**Comment by jonkpirateboy** [comment]
Reopened this to avoid more duplicate issues.

**Comment by imAraam** [comment]
If I understand correct our problem is the excess cache? Cant we append the JS path name to a dynamic value?

**Comment by jonkpirateboy** [comment]
No, it's a cookie problem.

**Comment by phink3n** [comment]
Som jag skrev i ett mail till @jonkpirateboy får jag ett `405 - HTTP verb used to access this page not available` direkt efter trycker på "Första möjliga tid innan --". Cookies är rensade pre detta problem. Är detta relaterat till denna issue?

**Comment by jonkpirateboy** [comment]
Jepp

**Comment by AriGolden** [comment]
Eftersom de kollar efter cookies som scriptet sätter ( TimeSearch / responseText ) och ballar ur om de finns (oavsett om man byter namn) borde man inte kunna använda GM_setValue istället?  Så att inte skapa cookies (som de kollar efter) och ändå behålla samma funktionalitet?

**Comment by stefanedberg** [comment]
Hinner inte göra en PR just nu men byt ut Cookie mot localStorage. Kan vara bra att byta nyckel också.
```
Cookies.set -> localStorage.setItem
Cookies.get -> localStorage.getItem
Cookies.remove -> localStorage.removeItem
```

**Comment by haegg78** [comment]
> Hinner inte göra en PR just nu men byt ut Cookie mot localStorage. Kan vara bra att byta nyckel också.
> 
> ```
> Cookies.set -> localStorage.setItem
> Cookies.get -> localStorage.getItem
> Cookies.remove -> localStorage.removeItem
> ```

Skapade en PR baserat på ditt förslag som fungerar. Har testat med ett datum i november
