### ISSUE TITLE
Is the new version working?

### ISSUE THREAD

**Issue by Sebastian-D** [jonkpirateboy/Pass-fur-alle#65]
Hi! Thanks for updating this. Regrettably the new version doesn't seem to work for me. I am running chrome and tampermonkey says that the script (which I have modified with new date) is active, but I don't see anything different on the timesearch page. Any help is appreciated.

Let me know what other info I could give to help.

Update: I got it working. Some weird hidden symbols from my editor tagged along in the copy paste. However I am getting same error as commenter below me now, badassbeef.

**Comment by badassbeef** [comment]
Hi, I am also running chrome, I see the dates that i configured in the script on timesearch page.
But I am getting this error instead:
ERR_TOO_MANY_REDIRECTS

**Comment by jonkpirateboy** [comment]
#62
