### ISSUE TITLE
Cross-linking

### ISSUE THREAD

**Issue by elias123tre** [jonkpirateboy/Pass-fur-alle#7]
I have created a similar script to yours, before even knowing about the one you made and they solve slightly different use cases. It would probably be helpful for everyone to cross-link these repositories.

Here is the script I made: https://github.com/elias123tre/passport_booker_se
It uses playwright (from Microsoft, by puppeteer developers) instead of selenium to minimize dependencies and manage installation with just one command and uses a graphical interface with Tkinter to ask the user about booking time, nr of people etc.

Feel free to add a link to my repo in your readme if it sounds interesting, I've already linked to yours from mine.

Ditt skript verkar riktigt bra och bland annat auto-bokning vilket är väldigt smidigt
Keep it up och Tack!

**Comment by jonkpirateboy** [comment]
Tackar! Jag har länkat till ditt repo nu. :)

**Comment by kalkih** [comment]
@elias123tre @jonkpirateboy 

Roligt!

Jag har skrivit en nodejs lösning med fetch och cheerio, om ni vill fortsätta cross länkandet 🙂  
[kalkih/passport-appointment-bot](https://github.com/kalkih/passport-appointment-bot)

**Comment by elias123tre** [comment]
> @elias123tre @jonkpirateboy 
> 
> Roligt!
> 
> Jag har skrivit en nodejs lösning med fetch och cheerio, om ni vill fortsätta cross länkandet 🙂  
> [kalkih/passport-appointment-bot](https://github.com/kalkih/passport-appointment-bot)

Snyggt implementerat! Jag skrev först min i nodejs med Playwright men ville ha cross-platform gui med tkinter ;) Tycker det är ett stort plus att kunna compila till alla targets med nodejs, blir mycket lättare för de otekniska slutanvändarna :) Jag ska länka till den i mitt repo också!

**Comment by elias123tre** [comment]
@jonkpirateboy @kalkih
Det kan dock vara bra att veta att dessa skript kommer sluta fungera under nästa vecka (så man får vara snabb om man ska ha en tid). Eventuellt kan det fortfarande funka men man behöver nog skriva om skriptet då

Källa: https://www.expressen.se/dinapengar/sa-ska-polisen-stoppa-fulbokningen-av-pass/
