### ISSUE TITLE
Error 801

### ISSUE THREAD

**Issue by HoneySue1337** [jonkpirateboy/Pass-fur-alle#70]
I'm using the latest version of the script, but cannot get into the site without getting the 801 error, see below. I'm on a Windows computer, running Chrome. Any ideas on how to solve this? (Have cleared cache and cookies before trying)

![error801](https://user-images.githubusercontent.com/103182486/162170554-e64793d0-75f7-4179-823b-46a88025d4df.png)

**Comment by Falkens-swe** [comment]
Same for me and it has become so in recent days

**Comment by jonkpirateboy** [comment]
Maybe your IP? Try a VPN or connecting through your phone.

**Comment by HoneySue1337** [comment]
Have tried both on my work VPN and without. Still the same response :/

**Comment by LucasJohansson** [comment]
I know you said you've tried clearing cookies, but I had the same issue and it only worked after clearing cookies through clicking here, and clearing that way:
![image](https://user-images.githubusercontent.com/16883017/162195287-c3691f90-d376-46fa-9ef4-da4d07ece16f.png)

**Comment by yoggi-yalla** [comment]
I had error 800 running Chrome on Mac, switched to Firefox and it worked, got a time the same day (today) after 30 mins of searching. Make sure to use the auto-confirm, otherwise any desirable time will most likely slip to someone else.

**Comment by HoneySue1337** [comment]
Clearing cookies like Lucas mentioned helped for now at least :)
I didn't seem to be able to select a specific expedition in my area though, but perhaps that's not possible? Would like to use auto-confirm, but only if I can search for expeditions I can easily actually get to.

**Comment by Falkens-swe** [comment]
> I know you said you've tried clearing cookies, but I had the same issue and it only worked after clearing cookies through clicking here, and clearing that way: ![image](https://user-images.githubusercontent.com/16883017/162195287-c3691f90-d376-46fa-9ef4-da4d07ece16f.png)

Thanks, now it's searching :-)

**Comment by Falkens-swe** [comment]
> Clearing cookies like Lucas mentioned helped for now at least :) I didn't seem to be able to select a specific expedition in my area though, but perhaps that's not possible? **Would like to use auto-confirm,** but only if I can search for expeditions I can easily actually get to.

Me to
