### ISSUE TITLE
Suggestion: Obfuscate the code before releasing

### ISSUE THREAD

**Issue by KianBrose** [jonkpirateboy/Pass-fur-alle#71]
I think I'm not the only one that thinks the people behind the booking website are actively watching this repository in order to see what solutions you come up with to then patch them. Maybe it would be a better idea to obfuscate "working" versions so that they can't see how it was fixed?

**Comment by Buggga** [comment]
> I think I'm not the only one that thinks the people behind the booking website are actively watching this repository in order to see what solutions you come up with to then patch them. Maybe it would be a better idea to obfuscate "working" versions so that they can't see how it was fixed?

It kind of brakes the rules of open source but I have to confess that I wrote the same suggestion to jonkpirateboy in a private message yesterday.

**Comment by KianBrose** [comment]
Yeah, I get the open source aspect but the problem here is that a service needs to be provided, and the fact that it is open source directly goes against the purpose of the project, so it's like stabbing yourself if that makes sense

**Comment by jonkpirateboy** [comment]
No, open source is the way.
