### ISSUE TITLE
Available time are not available.

### ISSUE THREAD

**Issue by Falkens-swe** [jonkpirateboy/Pass-fur-alle#72]
I get hits at different times but when I click (fast as hell) they are not available. Does it not work to do as before? To enter so the system does so you move on. That is, it automatically adds name + email + phone. (Auto confirm) 

Or it may not work in this version

**Comment by KianBrose** [comment]
They added a captcha there so that's not possible

**Comment by Falkens-swe** [comment]
> They added a captcha there so that's not possible

AAA I did see that now :-)

**Comment by KianBrose** [comment]
![captchas-everywhere](https://user-images.githubusercontent.com/62078964/162274444-7cb26001-d978-42ed-9add-fe1c979e0e5b.jpg)
