### ISSUE TITLE
Make window.location.reload(); instead of click button?

### ISSUE THREAD

**Issue by margu421** [jonkpirateboy/Pass-fur-alle#73]
To avoid having to timeout for 15 sec, I tried to change row 65 to reload page.
    setTimeout(function () {
                   // jQuery('input[name="' + localStorage.getItem('TimeSearch') + '"]').click();
                    window.location.reload();

**Comment by margu421** [comment]
It worked for me, got a time after about 15 min in Stockholm (well, "Sötälje").

**Comment by jonkpirateboy** [comment]
Does this work even if it has to load lots of times?

**Comment by margu421** [comment]
Yea, it allows me to request infinite numer of times at high frequency

**Comment by clindh** [comment]
This refresh method worked for me too, at least with "Next available" in a specific office - which I was after. 

I also tried "All offices", seemed to work fine as well - but the region I am in only has three offices - maybe Stockholm is harder.
