### ISSUE TITLE
Feature suggestion: Play a sound when a available time slot is found

### ISSUE THREAD

**Issue by jontelol** [jonkpirateboy/Pass-fur-alle#79]
Hey! Would be awesome if the script could play a sound when a time is found to avoid missing out on an available time slot because you were away from the computer at the time, or just didn't notice it.

https://www.w3schools.com/jsref/met_audio_play.asp

Thanks!

**Comment by jonkpirateboy** [comment]
Do it! https://github.com/jonkpirateboy/Pass-fur-alle/pulls

**Comment by jonkpirateboy** [comment]
https://github.com/jonkpirateboy/Pass-fur-alle/commit/a3dd5550bd6c77d6a667c175c4675648ee64a2d4
