### ISSUE TITLE
Can't confirm booking. Button's not responding.

### ISSUE THREAD

**Issue by dafvid** [jonkpirateboy/Pass-fur-alle#86]
Everything is working fine until I should click "Bekräfta bokning". The button's not responding. A request is being made but I'm not redirected and the booking is NOT confirmed. This is Chrome 100.0.4896.75 on MacOS 12.3.1. Gonna try Firefox next.

**Comment by cquencerr** [comment]
Same for me! It selects the time so it's got yellow but then doesn't progress. Using latest Safari on macOS

**Comment by dafvid** [comment]
Hm, this might be backend related. Getting 504s now.

**Comment by MaestroGarcia** [comment]
Had the same problem. But as you said this could be a backend problem and nothing to do with the script.
I got 504 and some internal server issues also.

But I also got this problem when you want to confirm "Bekräfta Bokning" nothing really happens. It tries and then you are back to confirm again?

**Comment by jonkpirateboy** [comment]
Are you searching for "Sök tid mellan ..." or "Första lediga tid..."?

**Comment by alexwpk** [comment]
Can confirm same issues - waiting a few hours to see if their backend issues are resolved.

**Comment by Falkens-swe** [comment]
a temporary problem that has been resolved or is it still pending?

**Comment by Falkens-swe** [comment]
Anyone tried to book an appointment without running the script?

**Comment by cquencerr** [comment]
Yes manually booking in November works fine

**Comment by Falkens-swe** [comment]
@jonkpirateboy Any thoughts / considerations?

**Comment by jonkpirateboy** [comment]
I just tested it (in Chrome), and it works. Will cancel the booking now.

**Comment by Falkens-swe** [comment]
> I just tested it (in Chrome), and it works. Will cancel the booking now.

Great news!!

**Comment by MaestroGarcia** [comment]
I used “sök mellan” . I run on PC with windows 10 and chrome. But what you are saying is that it is a backend problem?

**Comment by jonkpirateboy** [comment]
Yes
