### ISSUE TITLE
Q: - pls explain the option "autoConfirm"

### ISSUE THREAD

**Issue by ptrkbrgstrm** [jonkpirateboy/Pass-fur-alle#88]
Does the option "autoConfirm = true" work both for finding a new appointment and/or finding a time for re-booking? And, when enabled, does it automatically accept the first found time without prompting user or action, or how does it work?
Thanks in advance!

**Comment by jonkpirateboy** [comment]
It accepts the first time found, and it says *bling*, and you get to fill out your personal information.
