### ISSUE TITLE
Is it working for anyone?

### ISSUE THREAD

**Issue by nattzp** [jonkpirateboy/Pass-fur-alle#89]
I have had this running for several hours but not getting a time. Has it worked for anyone? Which button did you click in that case, time between --- and --- or the one for just before a certain date?

**Comment by Falkens-swe** [comment]
I made a booking 4 min ago and it worked. I always choose "Första Lediga Tid innan [Datum]"
Sometimes it books a random time later but then I just push back and start again.

**Comment by cquencerr** [comment]
Managed to get a time now in May as well so now it works great again. I used "Första lediga tid"

**Comment by nattzp** [comment]
Ok perfect thanks!! I will keep trying :)

**Comment by nattzp** [comment]
> I made a booking 4 min ago and it worked. I always choose "Första Lediga Tid innan [Datum]"
> Sometimes it books a random time later but then I just push back and start again.

What browser do you use? Chrome etc?

**Comment by jonkpirateboy** [comment]
Yes
