### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HubbaBubbaNew** [jonkpirateboy/Pass-fur-alle#9]
Hello My Friend. I get this error, what should I edit in vi to resolve this. If anybody knows please help. Thank You In Advance 

File "pass-fur-alle.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by Craktor** [comment]
Hi, I second that issue.

**Comment by danhir** [comment]
Sounds like a copy and paste issue. Python is indentation sensitive.
Try downloading the repo using git, GitHub desktop or download the zip package.

**Comment by jonkpirateboy** [comment]
What @danhir said.
