### ISSUE TITLE
Script switch from Search First available to Search specific date.

### ISSUE THREAD

**Issue by CrazySwede78** [jonkpirateboy/Pass-fur-alle#92]
Version 2.11
Windows 10
Chrome Version 100.0.4896.88 (Official Build) (64-bit)

Starting script with Search first available works as intended. However, after a while (Random amount of time, sometimes after 10 minutes, sometimes after 5 hours) the script goes from searching for first available to searching one date at a time from the specified date range.

Reloading the page or going back a step and then forward does not fix this. Instead, the whole window has to be closed and a new one opened, going from the start of Polisens regional booking page (Such as Search for time in Stockholms län) Edit - Relaunching Chrome completely also works to restore functionality of the script.

**Comment by jonkpirateboy** [comment]
If you bump into these kind of quirks clicking "Ärendekategorier", that clears the local storage.

**Comment by CrazySwede78** [comment]
> If you bump into these kind of quirks clicking "Ärendekategorier", that clears the local storage.

Ok, now I might be showing my ignorance, but where do I find "Ärendekategorier"?

**Comment by jonkpirateboy** [comment]
It has changed name to ”Boende”, it is in the blue top menu under the Polisen logo.

**Comment by CrazySwede78** [comment]
That solution doesn't work for me at least, but not sure if it is because of some local setting in my system or something else. In any case, I just wanted to raise awareness about it to you, just in case. Will close this issue after this. Thanks for taking the time and advice!
