### ISSUE TITLE
jQuery not defined

### ISSUE THREAD

**Issue by Blixtgo** [jonkpirateboy/Pass-fur-alle#93]
I am an amateur user,  Your code does not take over the buttons. Installed today into Firefox, everything went perfectly. I see that  In Tampermonkey  jQuery gets 'not defined'. Is that the reason? Contact me at william leaf gordon on messenger, thanks!

**Comment by Falkens-swe** [comment]
Try Google Chrome!

**Comment by jonkpirateboy** [comment]
I just tested it in Firefox, and it works fine. You have probably not pasted the code in Tampermonkey correctly. Make sure you replace whatever code is there, as stated in [the installation instructions](https://github.com/jonkpirateboy/Pass-fur-alle#install).

**Comment by Blixtgo** [comment]
Falkens and Jonk you are both right. and I thank you for quick replies. Jonk you should get a gold star! Imagine how many people you have helped.

**Comment by Blixtgo** [comment]
Hej! Smart! Det funkar! Jätte tack. /Bill

Hälsningar från våra katter. 🐱🐱🐱
________________________________
