### ISSUE TITLE
Times not selected

### ISSUE THREAD

**Issue by bera-n** [jonkpirateboy/Pass-fur-alle#95]
Having issues with the timeslot not selected when the script continues to confirm the booking. For some reason the onclick-event won't fire when the script clicks the timeslot. (The #timeSelectionText doesn't appear). Getting the "Du har inte valt någon tid." error
Tried this on both FF/Crome in w10 and FF in Linux

**Comment by jonkpirateboy** [comment]
Just tested on w10 FF and there's no problem there.
